# Generated by Django 4.0.5 on 2023-06-14 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0003_alter_usermodel_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='file_upload',
            new_name='profile_picture',
        ),
    ]
